image:
  file: .gitpod/Dockerfile
  context: .gitpod

tasks:
- name: frontend
  init: >
    yarn install && yarn build;
  command: >
    cd frontend;
    gatsby build && gatsby serve
- name: backend
  init: >
    cd backend;
    cargo build;
  command: >
    cd backend;
    cargo watch -w . -w ../protocol -x 'run -- 127.0.0.1:9090'
- name: grpc-web-proxy
  command: grpcwebproxy --backend_addr=localhost:9090 --run_tls_server=false --allow_all_origins
- command: "clear"

ports:
- port: 9000
  onOpen: open-browser
- port: 8080
  onOpen: ignore
- port: 9090
  onOpen: ignore