image:
  file: .gitpod/Dockerfile
tasks:
- name: frontend
  init: >
    cd frontend;
    yarn install
  command: >
    cd frontend;
    gatsby develop
- name: backend
  init: >
    cd backend;
    cargo build;
  command: >
    cd backend;
    cargo watch -x run
- command: ""