image:
  file: .gitpod/Dockerfile

tasks:
- name: frontend
  init: >
    yarn install && yarn build;
  command: >
    cd frontend;
    gatsby develop
- name: backend
  init: >
    cd backend;
    cargo build;
  command: >
    cd backend;
    cargo watch -x 'run -- 127.0.0.1:8080'
- command: "clear"

ports:
- port: 8000
  onOpen: open-preview