image:
  file: .gitpod/Dockerfile
  context: .gitpod

tasks:
- name: frontend
  init: >
    yarn install && yarn build;
  command: >
    cd frontend;
    gatsby develop
- name: backend
  init: >
    cd backend;
    cargo build;
  command: >
    cd backend;
    cargo watch -w . -w ../protocol -x 'run -- 127.0.0.1:9090'
- name: grpc-web-proxy
  command: grpcwebproxy --backend_addr=localhost:9090 --run_tls_server=false --allow_all_origins
- command: "clear"

ports:
# frontend: gatsby develop
- port: 8000
  onOpen: open-browser
# grpcwebproxy
- port: 8080
  onOpen: ignore
# backend
- port: 9090
  onOpen: ignore

vscode:
  extensions:
    - zxh404.vscode-proto3@0.3.0:4f1jn72vQA2/LVoVSSmMtQ==
